no faii

diff --git a/.github/workflows/vagrant_up.yaml b/.github/workflows/vagrant_up.yaml
--- a/.github/workflows/vagrant_up.yaml
+++ b/.github/workflows/vagrant_up.yaml
@@ -20,10 +20,10 @@ jobs:
         id: get-version
         run: |
           TAG=$(git describe --tags --abbrev=0)
-          if ! [[ $TAG =~ ^v[0-9]{2}\.[0-9]{2}\.[0-9]{2}$ ]]; then
-            echo "Invalid tag name: '$TAG'"
-            exit 1
-          fi
+          # if ! [[ $TAG =~ ^v[0-9]{2}\.[0-9]{2}\.[0-9]{2}$ ]]; then
+          #   echo "Invalid tag name: '$TAG'"
+          #   exit 1
+          # fi
           echo "version=${TAG:1}" >> $GITHUB_OUTPUT
       - name: Acquire Job ID
         if: failure()
